### ISSUE TITLE
Compiled release isn't working

### ISSUE THREAD

**Issue by Leshu7w7** [Sheelia/R3nzSkinTFT#6]
The compiled version injecting the SkinChanger from Regular matches instead the TFT one. I tried to compile the source, but it's giving an error at the moment of injecting (I'm new at compiling, so maybe that's the reason) Would you fix the compiled version pls?

**Comment by Sheelia** [comment]
https://github.com/Sheelia/R3nzSkinTFT/releases/tag/13.19 updated
