### ISSUE TITLE
Game crashes after using updated version for 13.18

### ISSUE THREAD

**Issue by eternal-art** [Sheelia/R3nzSkinTFT#7]
nothing much to say

**Comment by Sheelia** [comment]
compiled or released ?

**Comment by makabaka2869** [comment]
Hello, hello, will you always update this program in the future? Or is it just this version?

**Comment by Sheelia** [comment]
> Hello, hello, will you always update this program in the future? Or is it just this version?

I will always update

**Comment by makabaka2869** [comment]
> > 您好，您好，您将来会一直更新此程序吗？还是只是这个版本？
> 
> 我会一直更新

Thank you very much! Intersection Intersection Good luck! I love you! Intersection Intersection Love you very much! Intersection Intersection
