### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by YeojinDoLOONA** [Sheelia/R3nzSkinTFT#8]
when i try to use it, all works except for the injector, what you reccomend me?
![image_2023-09-29_155209474](https://github.com/Sheelia/R3nzSkinTFT/assets/117808966/d39b0dbd-9f55-45f9-9ab1-8fa06885ae8b)

**Comment by YeojinDoLOONA** [comment]
i use the compiled version btw

**Comment by Sheelia** [comment]
injector updated

**Comment by YeojinDoLOONA** [comment]
ok but i dont get it, i need to compile it by myself or what?

**Comment by YeojinDoLOONA** [comment]
Hello? 😭

**Comment by Sheelia** [comment]
https://github.com/Sheelia/R3nzSkinTFT/releases/tag/13.19 disable defender av

**Comment by YeojinDoLOONA** [comment]
when i press the "Change pet skin" the game crashes

**Comment by YeojinDoLOONA** [comment]
ok now it works, ty so munch, me and my boyfriend really love this
